### ISSUE TITLE
Add a OpenStreetMap to keep attention

### ISSUE THREAD

**Issue by jwitcoski** [osm-ar/mapazonia#11]
I added a commit to add openstreetmaps leaflet section to your website.  

![amazonia](https://cloud.githubusercontent.com/assets/5134087/6783726/be84d236-d151-11e4-949f-57c1c9866be7.JPG)

Just messing around with bootstrap and the leaflet api

Great job!!

**Comment by jwitcoski** [comment]
My internet is slow right now but I should be able to add tags #mapazonia to this map
using the taginfo api
http://taginfo.openstreetmap.org/keys/note#wiki
and overpass-turbo
http://overpass-turbo.eu/

**Comment by maurimiranda** [comment]
Per @jwitcoski suggestion, I've replaced the tasks section with a Leaflet map. Let me know if you think we should add/change something. Thanks @jwitcoski!

**Comment by jwitcoski** [comment]
Excellent Job!! Keep up the good work!!
